/* mvfs_when.h generated by make_when.pl - do not edit! */
#define ATRIA_IMAKE_INCLUDE /* necessary to avoid additional includes */
#include <tbs_major_ver_str.h> 
#define MVFS_WHEN_STRING "Fri Mar  4 21:48:23 2011" 
#define MVFS_VERSION_STRING "MVFS version " TBS_VER_MAJOR_ID " " "(Fri Mar  4 21:48:23 2011)\n" \
"(c) Copyright IBM Corp. 1990, 2011.  All Rights Reserved.\n"
#define MVFS_SCCSID_STRING "@(#) MVFS version " TBS_VER_MAJOR_ID " " "(Fri Mar  4 21:48:23 2011)"
#define MVFS_RCSID_STRING "$Header: MVFS version " TBS_VER_MAJOR_ID " " "(Fri Mar  4 21:48:23 2011) $"
